--뷰 이름은 자유
--1) 학생의 평점 4.5 만점으로 환산된 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_STUDENT_CONVERT_AVR (
	CONVERT_AVR
) AS (
	SELECT AVR * 1.125
		FROM STUDENT
);

--2) 각 과목별 기말고사 평균 점수를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_SCORE_AVG_RESULT (
	COURSE_NAME,
	AVG_RESULT
) AS (
	SELECT CNO
		 , AVG(RESULT)
		FROM SCORE
		GROUP BY CNO
);

--3) 각 사원과 관리자(MGR)의 이름을 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_EMP_MGR_NAME(
	EMP_NAME,
	MGR_NAME
) AS (
	SELECT E.ENAME
		 , E2.ENAME
		FROM EMP E
		JOIN EMP E2
		  ON E.MGR = E2.ENO
);


--4) 각 과목별 기말고사 평가 등급(A~F)까지와 해당 학생 정보를 검색할 수 있는 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_COURSE_GRADE_STINFO (
	SCG_GRADE,
	STUDENT_NUM,
	STUDENT_NAME,
	STUDENT_SEX,
	STUDENT_SYEAR,
	STUDENT_MAJOR,
	STUDENT_AVR
) AS (
	SELECT SCG.GRADE
		 , ST.SNO
		 , ST.SNAME
		 , ST.SEX
		 , ST.SYEAR
		 , ST.MAJOR
		 , ST.AVR
		FROM SCORE SC
		JOIN SCGRADE SCG
		  ON SC.RESULT BETWEEN LOSCORE AND HISCORE
		JOIN STUDENT ST
		  ON SC.SNO = ST.SNO
);


--5) 물리학과 교수의 과목을 수강하는 학생의 명단을 검색할 뷰를 생성하세요.
CREATE OR REPLACE VIEW V_PHYSICSPROF_COURSE_STUDENT (
	STUDENT_NAME
) AS (
	SELECT DISTINCT ST.SNAME
		FROM STUDENT ST
		JOIN SCORE SC
		  ON ST.SNO = SC.SNO
		JOIN COURSE C
		  ON SC.CNO = C.CNO
		JOIN PROFESSOR P
		  ON C.PNO = P.PNO
		WHERE P.SECTION = '물리'
);


