-- HOMEWORK

--1) 전공과 전공별 기말고사 평균 점수를 갖는 테이블
--   T_MAJOR_AVG_RES를 생성하고 SCORE테이블과 STUDENT테이블을 참조해서
--   T_MAJOR_AVG_RES에 데이터를 저장하는 프로시저 P_MAJOR_AVG_RES를 생성하세요.

CREATE TABLE T_MAJOR_AVG_RES(
	MAJOR VARCHAR2(20),
    AVG_SCORE NUMBER(5, 2)
);



CREATE OR REPLACE PROCEDURE P_MAJOR_AVG_RES IS
	CURSOR CUR_ST_SC_AVG IS
	SELECT ST.MAJOR
          , AVG(SC."RESULT") AS AV_SCORE
          FROM SCORE SC
          JOIN STUDENT ST
          ON ST.SNO = SC.SNO
          GROUP BY ST.MAJOR;
BEGIN
	FOR ST_SC_AVG_ROW IN CUR_ST_SC_AVG LOOP
		INSERT INTO T_MAJOR_AVG_RES (MAJOR, AVG_SCORE)
		VALUES (ST_SC_AVG_ROW.MAJOR, ST_SC_AVG_ROW.AV_SCORE);
	END LOOP;
	COMMIT;
END;

EXEC P_MAJOR_AVG_RES;

SELECT *
	FROM T_MAJOR_AVG_RES
	ORDER BY MAJOR;
          




--2) 교수들은 부임일로부터 5년마다 안식년을 갖습니다.
--   교수들의 오늘날짜까지의 안식년 횟수를 리턴하는 함수 F_GET_VACATION_CNT를 구현하세요.

CREATE OR REPLACE FUNCTION F_GET_VACATION_CNT(
	PARAM_DATE DATE
)
RETURN NUMBER
IS 
	COUNT_MONTHS NUMBER;
BEGIN 
		COUNT_MONTHS := MONTHS_BETWEEN(SYSDATE, PARAM_DATE); 
	RETURN TRUNC((COUNT_MONTHS/60), 0);
END;

SELECT F_GET_VACATION_CNT(TO_DATE('19800603', 'YYYYMMDD'))
FROM DUAL;
