--1) 과목번호, 과목이름, 과목별 평균 기말고사 성적을 갖는 레코드의 배열을 만들고
--   기본 LOOP문을 이용해서 모든 과목의 과목번호, 과목이름, 과목별 평균 기말고사 성적을 출력하세요.
DECLARE
	TYPE COURSE_RES_REC IS RECORD(
		CNO COURSE.CNO%TYPE,
		CNAME COURSE.CNAME%TYPE,
		AVG_RESULT NUMBER
	);

	CURSOR COURSE_RES_CUR IS 
		SELECT C.CNO
			 , C.CNAME
			 , ROUND(AVG(SC.RESULT), 2)
			FROM COURSE C
			JOIN SCORE SC
			  ON C.CNO = SC.CNO
			GROUP BY C.CNO, C.CNAME;

	TYPE AVG_RES_ARR IS TABLE OF COURSE_RES_REC
	INDEX BY PLS_INTEGER;
	
	IDX NUMBER := 1;
	AVGRESARR AVG_RES_ARR;
BEGIN
	OPEN COURSE_RES_CUR;
	
	LOOP
		FETCH COURSE_RES_CUR INTO AVGRESARR(IDX);
		
		EXIT WHEN COURSE_RES_CUR%NOTFOUND;
	
		DBMS_OUTPUT.PUT_LINE(AVGRESARR(IDX).CNO);
		DBMS_OUTPUT.PUT_LINE(AVGRESARR(IDX).CNAME);
		DBMS_OUTPUT.PUT_LINE(AVGRESARR(IDX).AVG_RESULT);
	
		IDX := IDX + 1;

	END LOOP;

	CLOSE COURSE_RES_CUR;
END;


--2) 학생번호, 학생이름과 학생별 평균 기말고사 성적을 갖는 테이블 T_STAVGSC를 만들고
--   커서를 이용하여 학생번호, 학생이름, 학생별 평균 기말고사 성적을 조회하고 
--   조회된 데이터를 생성한 테이블인 T_STAVGSC에 저장하세요.

CREATE TABLE T_STAVGSC (
	SNO VARCHAR2(8),
	SNAME VARCHAR2(20),
	AVG_RESULT NUMBER
);

DROP TABLE T_STAVGSC;
		 
DECLARE
	CURSOR CUR_STAVGSC IS
		SELECT ST.SNO
			 , ST.SNAME
			 , ROUND(AVG(SC.RESULT), 2) AS AVG_RESULT
		  FROM STUDENT ST
		  JOIN SCORE SC
		    ON ST.SNO = SC.SNO
		  GROUP BY ST.SNO, ST.SNAME;
	
	STAVGSC_ROW T_STAVGSC%ROWTYPE;
BEGIN
	OPEN CUR_STAVGSC;
	
	LOOP
		FETCH CUR_STAVGSC INTO STAVGSC_ROW;
		
		EXIT WHEN CUR_STAVGSC%NOTFOUND;
		
		INSERT INTO T_STAVGSC
		VALUES STAVGSC_ROW;
		COMMIT;
		
	END LOOP;
	
	CLOSE CUR_STAVGSC;
END;

SELECT *
	FROM T_STAVGSC;


